regro/rever

tests/conftest.py

Don't know if you want this or not. Here it is if you do.

Uncomment tempdir removing in the tests

---

docs/api/changelog.rst
docs/api/tag_activity.rst
docs/api/version_bump.rst
rever/activities/changelog.xsh
rever/activities/tag.xsh
rever/activities/version_bump.xsh
rever/environ.xsh
rever/logger.xsh

There are probably going to be a lot of activities, so this should keep them
organized better.

Move activities into rever/activities submodule

---

rever/logger.xsh

Implements simpler log caching

reimplement log caching

---

tests/test_conda.xsh

Once https://github.com/gforsyth/xonda/pull/12 is merged and released this can
be merged.

Remove xonda workaround

---

rever/main.xsh
tests/test_main.py

Version config fix

---

rever/activity.xsh

Don't call git reset --hard in the default activity

---

docs/index.rst

add quick start to website

---

.gitignore
docs/activities.rst
docs/conf.py
docs/index.rst

Activity table

---

rever.xsh

FIX: rever now includes comma in setup.py

---

rever/activities/changelog.xsh

fixes broken test

---

rever/tools.xsh
tests/test_tools.py

added indir context manager

---

rever/dag.py

more informative keyerror on dag

---

rever.xsh
rever/activities/ghpages.xsh
rever/docker.xsh
rever/environ.xsh
tests/test_ghpages_activity.py

Adds an activity to deploy to github pages.  Also, fixed the docker mount code to work on older versions of the docker run api

GitHub pages

---

rever/activities/changelog.xsh
rever/activity.xsh
rever/main.xsh
scripts/setup

Helper for those projects which haven't been graced by rever yet and would like to get started quickly.

WIP: add setup script

---

news/lws.rst
rever/tools.xsh
tests/test_tools.py

Should close #50 CC @CJ-Wright

pattern matching will capture and replace leading whitespace

---

news/suser.rst
rever/activities/sphinx.xsh
rever/environ.xsh
rever/tools.xsh

Makes the sphinx docs less annoying to deal with on the host

Sphinx user

---

docs/usepatterns.rst
news/log_version.rst
rever/activity.xsh
rever/logger.xsh
rever/main.xsh
tests/test_conda_forge_activity.py
tests/test_main.py

ENH: add kwargs and version to log

---

news/conda_forge_fork.rst
rever/activities/conda_forge.xsh
tests/test_conda_forge_activity.py

ENH: if fork doesn't exist create one

---

news/auth.rst
rever/github.xsh

This came up on my local machine while trying to issue a pyne release, so thought it would be worth fixing.

improved token authorization handling

---

docs/api/activity.rst
docs/index.rst
rever/activities/push_tag.xsh

some minor push tag doc fixes

---

news/ge.rst
rever/activities/push_tag.xsh

fixed push tag undoer

---

news/ghrelease_prepend.rst
rever/activities/ghrelease.xsh

ENH: allow users to prepend to the GHRELEASE

---

.gitignore
news/ghrelassets.rst
rever/activities/ghrelease.xsh

GitHub Release Assets

---

news/remove_none.rst
rever/activities/changelog.xsh
tests/test_changelog.py

move from ``None`` to ``* <add entry>`` news syntax.

replace None syntax with * <add entry> (with no API breakage)

---

news/fix_cf_url.rst
rever/activities/conda_forge.xsh

FIX: now we search for the rever generated tarball with the actual

---

news/verkey.rst
rever/main.xsh

minor fix to make command run on old rever/ dirs that might be hanging around

version key entry test

---

news/ftp.rst
rever/tools.xsh
tests/test_tools.py

fix for FTP urls

---

docs/api/activities/docker.rst
news/docker.rst
rever/activities/docker.xsh
rever/environ.xsh

Adds docker activities for building and pushing custom docker containers

Docker Activities

---

news/native_git_remote.rst
rever/activities/push_tag.xsh

inspect protocol

---

news/dockin.rst
rever/activities/docker.xsh
rever/conda.xsh
rever/main.xsh
tests/test_main.py

CC @regro/auto-tick - needed for conda-metachannel

Docker build fix

---

news/atest.rst
rever.xsh
rever/environ.xsh
rever/main.xsh

And also a couple of minor string dep warnings.

fixes force option

---

news/clauth.rst
rever/activities/changelog.xsh
rever/authors.xsh
rever/environ.xsh
tests/test_changelog.py

This includes many updates to make the changelog activity a lot more general, such that it can be used on a variety of projects, such as conda-build. CC @regro/auto-tick @CJ-Wright

Changelog authors

---

rever/activities/changelog.xsh
rever/authors.xsh
tests/test_changelog.py

CC @CJ-Wright - no news needed because fixes another PR

bugfixes for author reporting

---

news/authors-to-latest.rst
rever/activities/changelog.xsh

fixes minor issue CC @CJ-Wright

authores to release

---

rever/activity.xsh
rever/github.xsh

some minor check fixes

---

news/email.rst
rever/vcsutils.xsh

email fixes

---

news/write-authors.rst
rever/authors.xsh

update_authors to always write

---

news/add_version_output
rever/main.xsh

Would it be of interest to add something to read the version from git?  versioneer or otherwise?  I find it helpful to capture dev state.  That's sort of orthogonal to this PR, but let me know.

add --version flag to argparse

---

rever/activity.xsh

Adding 2 missing spaces on the "package not found" error msg message.

missing spaces

---

news/conda-base.rst
rever/docker.xsh
rever/environ.xsh
tests/test_docker.py

Conda base

---

news/fix-pypi-check.rst
rever/activities/pypi.xsh

This happened literally just today.  I really wish they had an API for this

pypi maintainer check fix

---

news/appimage.rst
rever/activities/appimage.xsh
rever/activities/ghrelease.xsh
rever/environ.xsh
tests/test_appimage.py

Rever AppImage activity is used to add xonsh AppImage - https://github.com/xonsh/xonsh/pull/3559

AppImage Activity

---

docs/index.rst
tests/test_pypi_activity.py
tests/test_tools.py

raw strings

---

.circleci/config.yml
.travis.yml
news/oauth_fix.rst
rever/github.xsh
setup.py
tests/test_github.py

This should fix the broken login behavior. I don't personally use regro so I don't have any projects I can test it on, but I was able to successfully authorize  and login using the new code.

Fixed broken github login behavior

---

docs/conf.py
news/sphinx_fix.rst

changed `doc_configurable` flag in `docs/conf.py` to `is_configurable`

fixing sphinx behavior

---

news/ghrel-target.rst
rever/activities/ghrelease.xsh

GHRELEASE_TARGET

---

rever/activities/pypi.xsh
tests/conftest.py
tests/test_pypi_activity.py

Add --dist-dir to every dist command when building for PyPI
